version: 2

project_name: terraform-provider-mycloud

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-mycloud
    main: ./
    binary: terraform-provider-mycloud_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
      - openbsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: "386"
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256


release:
  draft: false

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
