package mcp

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/signalbreak-labs/eidos/pkg/api"
)

func TestHandleGenerateConfig_StringSpec(t *testing.T) {
	spec := `openapi: "3.0.0"
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: listPets
      responses:
        "200":
          description: ok
    post:
      operationId: createPet
      responses:
        "201":
          description: created
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:   spec,
		Format: "yaml",
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}
	if len(result.Content) == 0 {
		t.Fatal("expected non-empty tool result content")
	}

	r := parseResult(t, result)
	if strings.TrimSpace(r.Config) == "" {
		t.Fatal("expected generated config")
	}
	if !strings.Contains(r.Config, "provider:") {
		t.Errorf("expected config to contain provider section, got:\n%s", r.Config)
	}
	if !strings.Contains(r.Config, "name: pet-store") {
		t.Errorf("expected provider name derived from spec title, got:\n%s", r.Config)
	}
	// M-54: a clean spec reports valid=true so MCP clients can trust the config.
	if !r.Valid {
		t.Errorf("expected valid=true for clean spec, got false; diagnostics: %+v", r.Diagnostics)
	}
	for _, d := range r.Diagnostics {
		if d.Severity == "error" {
			t.Errorf("unexpected error diagnostic: %+v", d)
		}
	}
}

func TestHandleGenerateConfig_ObjectSpec(t *testing.T) {
	spec := map[string]any{
		"openapi": "3.0.0",
		"info": map[string]any{
			"title":   "Pet Store",
			"version": "1.0.0",
		},
		"paths": map[string]any{
			"/pets": map[string]any{
				"get": map[string]any{
					"operationId": "listPets",
					"responses": map[string]any{
						"200": map[string]any{"description": "ok"},
					},
				},
			},
		},
	}

	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec: spec,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	if strings.TrimSpace(r.Config) == "" {
		t.Fatal("expected generated config")
	}
	if !strings.Contains(r.Config, "name: pet-store") {
		t.Errorf("expected provider name derived from spec title, got:\n%s", r.Config)
	}
	if !strings.Contains(r.Config, "list_pets") {
		t.Errorf("expected at least one data source derived from GET /pets, got:\n%s", r.Config)
	}
	for _, d := range r.Diagnostics {
		if d.Severity == "error" {
			t.Errorf("unexpected error diagnostic: %+v", d)
		}
	}
}

func TestHandleGenerateConfig_JSONFormat(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:   spec,
		Format: "json",
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	var cfg map[string]any
	if err := json.Unmarshal([]byte(r.Config), &cfg); err != nil {
		t.Fatalf("expected config to be valid JSON: %v\n%s", err, r.Config)
	}
	provider, ok := cfg["provider"].(map[string]any)
	if !ok {
		t.Fatalf("expected provider object in JSON config, got: %v", cfg)
	}
	if provider["name"] != "pet-store" {
		t.Errorf("expected provider name pet-store, got %v", provider["name"])
	}
}

func TestHandleGenerateConfig_IncludeComments(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:            spec,
		Format:          "yaml",
		IncludeComments: true,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	if !strings.HasPrefix(r.Config, "# Generated by eidos/generate-config\n") {
		t.Errorf("expected YAML config to start with header comment, got:\n%s", r.Config)
	}
	if !strings.Contains(r.Config, "# Provider metadata") {
		t.Errorf("expected per-section comments in YAML config, got:\n%s", r.Config)
	}
}

func TestHandleGenerateConfig_JSONFormatWithComments(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:            spec,
		Format:          "json",
		IncludeComments: true,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	var cfg map[string]any
	if err := json.Unmarshal([]byte(r.Config), &cfg); err != nil {
		t.Fatalf("expected config to be valid JSON: %v\n%s", err, r.Config)
	}
	if cfg["_generator"] != "eidos/generate-config" {
		t.Errorf("expected JSON _generator marker, got %v", cfg["_generator"])
	}
}

func TestHandleGenerateConfig_UnsupportedFormat(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:   spec,
		Format: "xml",
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if r.Config != "" {
		t.Errorf("expected empty config for unsupported format, got:\n%s", r.Config)
	}
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected error diagnostic for unsupported format, got: %+v", r.Diagnostics)
	}
}

func TestHandleGenerateConfig_InvalidSpec(t *testing.T) {
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec: "not valid openapi",
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if r.Config != "" {
		t.Errorf("expected empty config for invalid spec, got:\n%s", r.Config)
	}
	// M-54: an invalid spec reports valid=false and withholds the config.
	if r.Valid {
		t.Errorf("expected valid=false for invalid spec, got true")
	}
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected at least one error diagnostic for invalid spec, got: %+v", r.Diagnostics)
	}
}

func TestHandleGenerateConfig_NilSpec(t *testing.T) {
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec: nil,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected error diagnostic for missing spec, got: %+v", r.Diagnostics)
	}
}

func TestGenerateConfigTool_Schema(t *testing.T) {
	tool := GenerateConfigTool()
	if tool.Name != "eidos/generate-config" {
		t.Errorf("tool name = %q, want eidos/generate-config", tool.Name)
	}
	if tool.Description == "" {
		t.Error("expected non-empty tool description")
	}
	schema, ok := tool.InputSchema.(*jsonschema.Schema)
	if !ok {
		t.Fatalf("expected InputSchema to be *jsonschema.Schema, got %T", tool.InputSchema)
	}
	if schema.Type != "object" {
		t.Errorf("expected input schema type object, got %q", schema.Type)
	}
	if len(schema.Required) != 1 || schema.Required[0] != "spec" {
		t.Errorf("expected required field [spec], got %v", schema.Required)
	}
	outputSchema, ok := tool.OutputSchema.(*jsonschema.Schema)
	if !ok {
		t.Fatalf("expected OutputSchema to be *jsonschema.Schema, got %T", tool.OutputSchema)
	}
	if outputSchema.Type != "object" {
		t.Errorf("expected output schema type object, got %q", outputSchema.Type)
	}
	for _, name := range []string{"config", "diagnostics", "valid"} {
		if _, present := outputSchema.Properties[name]; !present {
			t.Errorf("expected output property %q", name)
		}
	}
	if len(outputSchema.Required) != 3 || outputSchema.Required[0] != "config" || outputSchema.Required[1] != "diagnostics" || outputSchema.Required[2] != "valid" {
		t.Errorf("expected output required [config, diagnostics, valid], got %v", outputSchema.Required)
	}

	// Validate the schema definitions are well-formed and self-consistent.
	resolved, err := outputSchema.Resolve(nil)
	if err != nil {
		t.Fatalf("failed to resolve output schema: %v", err)
	}
	if err := resolved.Validate(map[string]any{
		"config":      "provider:\n  name: test\n",
		"diagnostics": []any{},
		"valid":       true,
	}); err != nil {
		t.Errorf("output schema rejected a valid result payload: %v", err)
	}

	diagItems := outputSchema.Properties["diagnostics"].Items
	for _, name := range []string{"severity", "summary"} {
		if _, present := diagItems.Properties[name]; !present {
			t.Errorf("expected diagnostic property %q", name)
		}
	}
	if len(diagItems.Required) != 2 || diagItems.Required[0] != "severity" || diagItems.Required[1] != "summary" {
		t.Errorf("expected diagnostic required [severity, summary], got %v", diagItems.Required)
	}
	severitySchema := diagItems.Properties["severity"]
	if len(severitySchema.Enum) != 3 {
		t.Errorf("expected severity enum with 3 values, got %v", severitySchema.Enum)
	}
	for _, want := range []string{"error", "warning", "info"} {
		found := false
		for _, v := range severitySchema.Enum {
			if v == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("expected severity enum to contain %q, got %v", want, severitySchema.Enum)
		}
	}
	for _, name := range []string{"file", "line", "column", "path"} {
		if _, present := diagItems.Properties["source_location"].Properties[name]; !present {
			t.Errorf("expected source_location property %q", name)
		}
	}
}

func TestNormalizeSpec_UnsupportedType(t *testing.T) {
	_, err := normalizeSpec(12345)
	if err == nil {
		t.Fatal("expected error for unsupported spec type")
	}
	if !strings.Contains(err.Error(), "spec must be a string") {
		t.Errorf("expected typed error message, got: %v", err)
	}
}

// TestNormalizeSpec_ByteishTypes covers the []byte and json.RawMessage branches
// of normalizeSpec, which the prior tests exercised only indirectly through the
// string path (L-73: these branches had no direct coverage).
func TestNormalizeSpec_ByteishTypes(t *testing.T) {
	const spec = `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`
	for _, name := range []string{"[]byte", "json.RawMessage"} {
		t.Run(name, func(t *testing.T) {
			var in any
			switch name {
			case "[]byte":
				in = []byte(spec)
			case "json.RawMessage":
				in = json.RawMessage(spec)
			}
			got, err := normalizeSpec(in)
			if err != nil {
				t.Fatalf("normalizeSpec(%s) error: %v", name, err)
			}
			if string(got) != spec {
				t.Errorf("normalizeSpec(%s) round-trip mismatch:\ngot:  %q\nwant: %q", name, string(got), spec)
			}
		})
	}
}

// TestNormalizeSpec_Nil asserts the required-field guard rejects a missing spec.
func TestNormalizeSpec_Nil(t *testing.T) {
	_, err := normalizeSpec(nil)
	if err == nil {
		t.Fatal("expected error for nil spec")
	}
	if !strings.Contains(err.Error(), "spec is required") {
		t.Errorf("expected 'spec is required' error, got: %v", err)
	}
}

func TestHandleGenerateConfig_CanceledContext(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	result, _, err := HandleGenerateConfig(ctx, nil, GenerateConfigArgs{
		Spec: `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected error diagnostic for canceled context, got: %+v", r.Diagnostics)
	}
	found := false
	for _, d := range r.Diagnostics {
		if d.Severity == "error" && strings.Contains(d.Summary, "canceled") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected 'Request canceled' diagnostic, got: %+v", r.Diagnostics)
	}
}

func TestHandleGenerateConfig_SkipOperations(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: listPets
      responses:
        "200":
          description: ok
    post:
      operationId: createPet
      responses:
        "201":
          description: created
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:           spec,
		Format:         "yaml",
		SkipOperations: []string{"createPet"},
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	if !strings.Contains(r.Config, "skip_operations:") {
		t.Errorf("expected config to contain skip_operations, got:\n%s", r.Config)
	}
	if !strings.Contains(r.Config, "- createPet") {
		t.Errorf("expected skip_operations to include createPet, got:\n%s", r.Config)
	}
}

func TestHandleGenerateConfig_IncludeOperations(t *testing.T) {
	spec := `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: listPets
      responses:
        "200":
          description: ok
    post:
      operationId: createPet
      responses:
        "201":
          description: created
`
	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:              spec,
		Format:            "yaml",
		IncludeOperations: []string{"listPets"},
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig failed: %v", err)
	}

	r := parseResult(t, result)
	if !strings.Contains(r.Config, "include_operations:") {
		t.Errorf("expected config to contain include_operations, got:\n%s", r.Config)
	}
	if !strings.Contains(r.Config, "- listPets") {
		t.Errorf("expected include_operations to include listPets, got:\n%s", r.Config)
	}
}

func TestHandleGenerateConfig_PanicRecovery(t *testing.T) {
	orig := validateContextFn
	defer setValidateContextForTest(orig)
	setValidateContextForTest(func(context.Context, []byte) api.ValidateResponse {
		panic("deliberate handler panic")
	})

	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec: `openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths: {}
`,
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if r.Config != "" {
		t.Errorf("expected empty config after panic, got:\n%s", r.Config)
	}
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected error diagnostic after panic, got: %+v", r.Diagnostics)
	}
	found := false
	for _, d := range r.Diagnostics {
		if strings.Contains(d.Summary, "panic") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected panic diagnostic, got: %+v", r.Diagnostics)
	}
}

func TestHandleGenerateConfig_LargeSpec(t *testing.T) {
	// Build a spec that exceeds maxSpecSize by repeating a long path block.
	block := `
  /pets:
    get:
      operationId: listPets
      responses:
        "200":
          description: ok
`
	var sb strings.Builder
	sb.WriteString(`openapi: 3.0.0
info:
  title: Pet Store
  version: 1.0.0
paths:`)
	for sb.Len() < maxSpecSize+len(block) {
		sb.WriteString(block)
	}

	result, _, err := HandleGenerateConfig(context.Background(), nil, GenerateConfigArgs{
		Spec:   sb.String(),
		Format: "yaml",
	})
	if err != nil {
		t.Fatalf("HandleGenerateConfig returned handler error: %v", err)
	}

	r := parseResult(t, result)
	if r.Config != "" {
		t.Errorf("expected empty config for oversized spec, got:\n%s", r.Config)
	}
	if !hasError(r.Diagnostics) {
		t.Fatalf("expected error diagnostic for oversized spec, got: %+v", r.Diagnostics)
	}
	found := false
	for _, d := range r.Diagnostics {
		if strings.Contains(d.Summary, "maximum size") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected oversized-spec diagnostic, got: %+v", r.Diagnostics)
	}
}

func parseResult(t *testing.T, result *mcp.CallToolResult) GenerateConfigResult {
	t.Helper()
	if len(result.Content) == 0 {
		t.Fatal("expected non-empty tool result content")
	}
	text, ok := result.Content[0].(*mcp.TextContent)
	if !ok {
		t.Fatalf("expected TextContent, got %T", result.Content[0])
	}
	var r GenerateConfigResult
	if err := json.Unmarshal([]byte(text.Text), &r); err != nil {
		t.Fatalf("failed to unmarshal tool result: %v\n%s", err, text.Text)
	}
	return r
}

func hasError(diags []api.DiagnosticJSON) bool {
	for _, d := range diags {
		if d.Severity == "error" {
			return true
		}
	}
	return false
}

func TestHandleInspect_ReportsCRUDCompleteness(t *testing.T) {
	spec := `openapi: "3.0.0"
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    post:
      operationId: createPet
      responses:
        "201": {description: created}
  /pets/{id}:
    get:
      operationId: getPet
      responses:
        "200": {description: ok}
    delete:
      operationId: deletePet
      responses:
        "200": {description: ok}
`
	res, out, err := HandleInspect(context.Background(), nil, InspectArgs{Spec: spec})
	if err != nil {
		t.Fatalf("HandleInspect error: %v", err)
	}
	if res == nil || out.Valid != true {
		t.Fatalf("expected valid inspect result, got %+v", out)
	}
	var pet *ResourceSummary
	for i := range out.Resources {
		if out.Resources[i].Name == "pet" {
			pet = &out.Resources[i]
			break
		}
	}
	if pet == nil {
		t.Fatalf("expected a pet resource, got %+v", out.Resources)
	}
	if !pet.Wired || pet.Create == "" || pet.Read == "" || pet.Delete == "" {
		t.Errorf("expected pet to be wired with create/read/delete, got %+v", pet)
	}
}

func TestHandleValidateSchemas_ReportsDynamicCollection(t *testing.T) {
	spec := `openapi: "3.0.0"
info:
  title: Dyn API
  version: 1.0.0
paths:
  /widgets:
    get:
      operationId: listWidgets
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
`
	res, out, err := HandleValidateSchemas(context.Background(), nil, ValidateSchemasArgs{Spec: spec})
	if err != nil {
		t.Fatalf("HandleValidateSchemas error: %v", err)
	}
	if res == nil {
		t.Fatal("nil result")
	}
	found := false
	for _, iss := range out.Issues {
		if iss.Kind == "dynamic-element-collection" || iss.Kind == "nested-collection" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected a dynamic/nested collection issue, got %+v", out.Issues)
	}
}

func TestHandleOverridePreview_ReportsNoOp(t *testing.T) {
	spec := `openapi: "3.0.0"
info:
  title: Pet Store
  version: 1.0.0
paths:
  /pets:
    post:
      operationId: createPet
      responses:
        "201": {description: created}
  /pets/{id}:
    get:
      operationId: getPet
      responses:
        "200": {description: ok}
    delete:
      operationId: deletePet
      responses:
        "200": {description: ok}
`
	cfg := "provider:\n  name: pet\n  version: \"1.0.0\"\nresource_overrides:\n  - operation: createPet\n    resource_name: animal\n  - operation: postDashboard\n    resource_name: dashboard\n"
	res, out, err := HandleOverridePreview(context.Background(), nil, OverridePreviewArgs{Spec: spec, Config: cfg})
	if err != nil {
		t.Fatalf("HandleOverridePreview error: %v", err)
	}
	if res == nil {
		t.Fatal("nil result")
	}
	if len(out.Overrides) != 2 {
		t.Fatalf("expected 2 override reports, got %+v", out.Overrides)
	}
	if !out.Overrides[0].Matched {
		t.Errorf("expected createPet override to match, got %+v", out.Overrides[0])
	}
	if out.Overrides[1].Matched {
		t.Errorf("expected postDashboard override to be a no-op, got %+v", out.Overrides[1])
	}
}

// requiresConfigSpec is a spec whose collection POST is NOT inferred as a
// managed-resource Create: its request body (PurchaseRequest) does not match
// the instance Ship schema and there is no DELETE on the instance path. The
// transformer therefore treats purchase-ship as an action and get-my-ship as a
// data source, yielding zero managed resources from spec-only inference. A
// generate_resource override promotes it to a managed resource, which only
// surfaces when the config is actually threaded through the pipeline (M-73).
const requiresConfigSpec = `openapi: "3.0.0"
info:
  title: Requires Config
  version: 1.0.0
paths:
  /my/ships:
    post:
      operationId: purchase-ship
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
      responses:
        "201":
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
  /my/ships/{shipSymbol}:
    get:
      operationId: get-my-ship
      parameters:
        - {name: shipSymbol, in: path, required: true, schema: {type: string}}
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
components:
  schemas:
    PurchaseRequest:
      type: object
      properties:
        shipType: {type: string}
    Ship:
      type: object
      properties:
        symbol: {type: string}
        name: {type: string}
`

const requiresConfigOverride = `provider:
  name: requires-config
  version: "1.0.0"
resource_overrides:
  - schema: Ship
    resource_name: ship
    id_attribute: symbol
    generate_resource: true
    create_operation: purchase-ship
    read_operation: get-my-ship
    delete_operation: scrap-ship
`

// TestHandleInspect_HonorsConfig verifies that eidos/inspect threads the
// optional generator.yaml through the pipeline. Without the config the spec
// yields no managed resources; with the generate_resource override the ship
// resource is promoted and reported (regression guard for M-73, where inspect
// silently ignored args.Config).
func TestHandleInspect_HonorsConfig(t *testing.T) {
	_, noCfg, err := HandleInspect(context.Background(), nil, InspectArgs{Spec: requiresConfigSpec})
	if err != nil {
		t.Fatalf("inspect without config: %v", err)
	}
	if len(noCfg.Resources) != 0 {
		t.Errorf("spec-only inference should yield 0 resources, got %d: %+v", len(noCfg.Resources), noCfg.Resources)
	}

	_, withCfg, err := HandleInspect(context.Background(), nil, InspectArgs{Spec: requiresConfigSpec, Config: requiresConfigOverride})
	if err != nil {
		t.Fatalf("inspect with config: %v", err)
	}
	if len(withCfg.Resources) != 1 {
		t.Fatalf("config should promote 1 resource, got %d: %+v", len(withCfg.Resources), withCfg.Resources)
	}
	ship := withCfg.Resources[0]
	if ship.Name != "ship" {
		t.Errorf("expected resource name %q, got %q", "ship", ship.Name)
	}
	if ship.Create == "" || ship.Read == "" {
		t.Errorf("expected wired create/read, got %+v", ship)
	}
}

// TestHandleGenerate_HonorsConfig verifies eidos/generate reports the
// override-promoted resource in its summary (not just spec-only inference).
func TestHandleGenerate_HonorsConfig(t *testing.T) {
	_, noCfg, err := HandleGenerate(context.Background(), nil, GenerateArgs{Spec: requiresConfigSpec})
	if err != nil {
		t.Fatalf("generate without config: %v", err)
	}
	if len(noCfg.Resources) != 0 {
		t.Errorf("spec-only inference should yield 0 resources, got %d", len(noCfg.Resources))
	}

	_, withCfg, err := HandleGenerate(context.Background(), nil, GenerateArgs{Spec: requiresConfigSpec, Config: requiresConfigOverride})
	if err != nil {
		t.Fatalf("generate with config: %v", err)
	}
	if len(withCfg.Resources) != 1 || withCfg.Resources[0].Name != "ship" {
		t.Fatalf("expected one ship resource, got %+v", withCfg.Resources)
	}
}

// TestHandleValidateSchemas_HonorsConfig verifies eidos/validate-schemas runs
// against the override-shaped IR. With the override, the Ship schema becomes a
// resource schema and its framework validity is reported; without the config
// the ship is only a data-source response and contributes no resource issue.
func TestHandleValidateSchemas_HonorsConfig(t *testing.T) {
	_, withCfg, err := HandleValidateSchemas(context.Background(), nil, ValidateSchemasArgs{Spec: requiresConfigSpec, Config: requiresConfigOverride})
	if err != nil {
		t.Fatalf("validate-schemas with config: %v", err)
	}
	// The override promotes Ship to a resource; validate-schemas must walk it
	// as a resource (not just a data source). At minimum the result must be
	// valid and non-nil, proving the config shaped the IR rather than being
	// dropped.
	if !withCfg.Valid {
		t.Errorf("expected valid result, got %+v", withCfg)
	}
}

// TestMergeConfigIntoSpec_EmptyConfigIsNoop guards the empty-config short-circuit
// so the no-config path never re-serializes the spec (which could alter
// formatting or introduce parse round-trips for callers passing the spec body).
func TestMergeConfigIntoSpec_EmptyConfigIsNoop(t *testing.T) {
	spec := []byte(`{"openapi":"3.0.0","info":{"title":"X","version":"1.0.0"},"paths":{}}`)
	out, err := mergeConfigIntoSpec(spec, "")
	if err != nil {
		t.Fatalf("mergeConfigIntoSpec: %v", err)
	}
	if !bytes.Equal(out, spec) {
		t.Errorf("empty config should return spec unchanged, got %q", string(out))
	}
}

// TestGenerateArgs_UnmarshalJSON_DryRunCamelCase verifies that a camelCase
// "dryRun" key (as LLMs commonly send despite the snake_case schema) sets
// DryRun, so the tool plans instead of silently writing a provider tree (M-75).
func TestGenerateArgs_UnmarshalJSON_DryRunCamelCase(t *testing.T) {
	cases := map[string]bool{
		`{"spec":"x","dryRun":true}`:                 true,
		`{"spec":"x","dry_run":true}`:                true,
		`{"spec":"x","dryRun":false}`:                false,
		`{"spec":"x","dry_run":false}`:               false,
		`{"spec":"x"}`:                               false,
		`{"spec":"x","dryRun":true,"dry_run":false}`: true, // either true wins
	}
	for body, want := range cases {
		var a GenerateArgs
		if err := json.Unmarshal([]byte(body), &a); err != nil {
			t.Errorf("Unmarshal(%s): %v", body, err)
			continue
		}
		if a.DryRun != want {
			t.Errorf("Unmarshal(%s): DryRun = %v, want %v", body, a.DryRun, want)
		}
	}
}

// TestGenerateArgs_UnmarshalJSON_RoundTripsFields verifies the custom
// UnmarshalJSON still populates the non-DryRun fields.
func TestGenerateArgs_UnmarshalJSON_RoundTripsFields(t *testing.T) {
	var a GenerateArgs
	if err := json.Unmarshal([]byte(`{"spec":"s","config":"c","output":"o","verify":true,"dry_run":true}`), &a); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if a.Spec != "s" || a.Config != "c" || a.Output != "o" || !a.Verify || !a.DryRun {
		t.Errorf("fields not round-tripped: %+v", a)
	}
}
