package generator

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/signalbreak-labs/eidos/pkg/ir"
)

// TestMainGoFile_Render verifies that MainGoFile emits a protocol-aware
// entry point that imports both v5 and v6 server packages and switches on
// the --protocol-version flag.
func TestMainGoFile_Render(t *testing.T) {
	cfg := BuildConfig{
		ProviderName: "mycloud",
		Namespace:    "acme",
	}

	file := MainGoFile(cfg)
	var buf bytes.Buffer
	if err := file.Render(&buf); err != nil {
		t.Fatalf("Render() error = %v", err)
	}
	got := buf.String()

	wantSubstrings := []string{
		"package main",
		"\"context\"",
		"\"flag\"",
		"\"fmt\"",
		"\"log\"",
		"\"github.com/hashicorp/terraform-plugin-framework/providerserver\"",
		"\"github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server\"",
		"\"github.com/acme/terraform-provider-mycloud/internal/provider\"",
		"flag.BoolVar(&debug, \"debug\"",
		"flag.IntVar(&protocolVersion, \"protocol-version\"",
		"flag.BoolVar(&printVersion, \"version\"",
		"address := \"registry.terraform.io/acme/mycloud\"",
		"if protocolVersion == 5",
		"tf5server.Serve(",
		"providerserver.NewProtocol5(provider.New())",
		"providerserver.Serve(context.Background(), provider.New, opts)",
		"Address: address",
		"Debug: debug",
		"warning: unsupported --protocol-version",
		"log.Printf(",
	}

	for _, want := range wantSubstrings {
		if !strings.Contains(got, want) {
			t.Errorf("generated main.go missing %q\ncontent:\n%s", want, got)
		}
	}

	// The var block is generated by astgen; its alignment can change.
	// Use regex checks that are agnostic to the exact whitespace/column alignment.
	wantRegexps := []*regexp.Regexp{
		regexp.MustCompile(`var\s*\(`),
		regexp.MustCompile(`version\s+string\s*=\s*"dev"`),
		regexp.MustCompile(`commit\s+string\s*=\s*"none"`),
		regexp.MustCompile(`date\s+string\s*=\s*"unknown"`),
	}
	for _, want := range wantRegexps {
		if !want.MatchString(got) {
			t.Errorf("generated main.go missing pattern %q\ncontent:\n%s", want.String(), got)
		}
	}

	// Confirm the build-time metadata variables are declared at package scope,
	// not inside func main(), so that -X main.version=... ldflags apply.
	assertPackageScopeVarBlock(t, got)
}

// TestMainGoFile_Render_CustomModulePath verifies that a custom ModulePath is
// reflected in the generated import path while the registry source address
// still uses the namespace and provider name.
func TestMainGoFile_Render_CustomModulePath(t *testing.T) {
	cfg := BuildConfig{
		ProviderName: "mycloud",
		Namespace:    "acme",
		ModulePath:   "example.com/custom/terraform-provider-mycloud",
	}

	file := MainGoFile(cfg)
	var buf bytes.Buffer
	if err := file.Render(&buf); err != nil {
		t.Fatalf("Render() error = %v", err)
	}
	got := buf.String()

	wantSubstrings := []string{
		"\"example.com/custom/terraform-provider-mycloud/internal/provider\"",
		"address := \"registry.terraform.io/acme/mycloud\"",
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(got, want) {
			t.Errorf("generated main.go missing %q\ncontent:\n%s", want, got)
		}
	}

	// The build-time metadata var block must be emitted independent of the
	// module path configuration.
	wantRegexps := []*regexp.Regexp{
		regexp.MustCompile(`var\s*\(`),
		regexp.MustCompile(`version\s+string\s*=\s*"dev"`),
		regexp.MustCompile(`commit\s+string\s*=\s*"none"`),
		regexp.MustCompile(`date\s+string\s*=\s*"unknown"`),
	}
	for _, want := range wantRegexps {
		if !want.MatchString(got) {
			t.Errorf("generated main.go missing pattern %q\ncontent:\n%s", want.String(), got)
		}
	}

	assertPackageScopeVarBlock(t, got)

	// The default module path based on the namespace must not appear.
	unwanted := "\"github.com/acme/terraform-provider-mycloud/internal/provider\""
	if strings.Contains(got, unwanted) {
		t.Errorf("generated main.go unexpectedly contains default import path %q\ncontent:\n%s", unwanted, got)
	}
}

// TestMainGoFile_BuildCompiles generates a minimal provider module and confirms
// that the generated main.go compiles successfully.
func TestMainGoFile_BuildCompiles(t *testing.T) {
	skipIfNetworkRestricted(t)
	providerIR := ir.ProviderIR{
		Name:        "mycloud",
		TypeName:    "mycloud",
		Description: "Generated provider for MyCloud.",
		ConfigSchema: ir.ObjectSchemaIR{
			Attributes: []ir.AttributeIR{
				{
					Name:        "api_key",
					Description: "API key authentication",
					Required:    true,
					Sensitive:   true,
					Schema:      ir.SchemaIR{Type: ir.TypeString},
				},
			},
		},
	}

	tmp := generateMainModule(t, providerIR)

	ctx, cancel := contextWithTimeout(t, 5*time.Minute)
	defer cancel()

	tidyCmd := exec.CommandContext(ctx, "go", "mod", "tidy")
	tidyCmd.Dir = tmp
	if out, err := tidyCmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy failed: %v\n%s", err, out)
	}

	buildCmd := exec.CommandContext(ctx, "go", "build", ".")
	buildCmd.Dir = tmp
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
}

// TestMainGoFile_BuildLdflags generates a minimal provider module, builds the
// binary with -X ldflags for version/commit/date, and asserts that running the
// binary with -version prints the injected values. This exercises the actual
// ldflag injection path used by GoReleaser.
func TestMainGoFile_BuildLdflags(t *testing.T) {
	skipIfNetworkRestricted(t)
	providerIR := ir.ProviderIR{
		Name:        "mycloud",
		TypeName:    "mycloud",
		Description: "Generated provider for MyCloud.",
		ConfigSchema: ir.ObjectSchemaIR{
			Attributes: []ir.AttributeIR{
				{
					Name:        "api_key",
					Description: "API key authentication",
					Required:    true,
					Sensitive:   true,
					Schema:      ir.SchemaIR{Type: ir.TypeString},
				},
			},
		},
	}

	tmp := generateMainModule(t, providerIR)

	ctx, cancel := contextWithTimeout(t, 5*time.Minute)
	defer cancel()

	tidyCmd := exec.CommandContext(ctx, "go", "mod", "tidy")
	tidyCmd.Dir = tmp
	if out, err := tidyCmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy failed: %v\n%s", err, out)
	}

	binaryName := "provider"
	if runtime.GOOS == "windows" {
		binaryName += ".exe"
	}
	binaryPath := filepath.Join(tmp, binaryName)

	buildCmd := exec.CommandContext(ctx, "go", "build", "-ldflags", "-X main.version=test -X main.commit=abc123 -X main.date=2026-07-06", "-o", binaryName, ".")
	buildCmd.Dir = tmp
	if out, err := buildCmd.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}

	versionCmd := exec.CommandContext(ctx, binaryPath, "-version")
	versionCmd.Dir = tmp
	out, err := versionCmd.CombinedOutput()
	if err != nil {
		t.Fatalf("running provider binary with -version failed: %v\n%s", err, out)
	}

	got := parseVersionOutput(t, string(out))
	want := map[string]string{
		"version": "test",
		"commit":  "abc123",
		"date":    "2026-07-06",
	}
	for key, wantVal := range want {
		if got[key] != wantVal {
			t.Errorf("version output %q = %q, want %q\nfull output:\n%s", key, got[key], wantVal, out)
		}
	}
}

// parseVersionOutput parses the key=value lines emitted by the generated
// provider binary when invoked with the -version flag.
func parseVersionOutput(t *testing.T, output string) map[string]string {
	t.Helper()
	result := make(map[string]string)
	for _, line := range strings.Split(strings.TrimSpace(output), "\n") {
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		result[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
	}
	return result
}

// generateMainModule writes the generated go.mod, provider.go, and main.go
// files into a temporary module directory and returns the module root.
func generateMainModule(t *testing.T, providerIR ir.ProviderIR) string {
	t.Helper()
	tmp := t.TempDir()

	cfg := BuildConfig{
		ProviderName: providerIR.Name,
		Namespace:    "acme",
	}

	h := Harness{OutputDir: tmp}
	pf, err := ProviderFile(providerIR)
	if err != nil {
		t.Fatalf("ProviderFile() error = %v", err)
	}
	files := append(BuildFiles(cfg), pf)
	if err := h.Generate(files); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	return tmp
}

// assertPackageScopeVarBlock parses generated main.go source and verifies that
// version, commit, and date are declared as package-level variables so that
// -X main.version=... style ldflags can override them at link time.
func assertPackageScopeVarBlock(t *testing.T, src string) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "main.go", src, parser.AllErrors)
	if err != nil {
		t.Fatalf("generated main.go is not valid Go: %v\n%s", err, src)
	}

	want := map[string]string{
		"version": "dev",
		"commit":  "none",
		"date":    "unknown",
	}

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range valueSpec.Names {
				wantDefault, ok := want[name.Name]
				if !ok {
					continue
				}
				delete(want, name.Name)
				if i >= len(valueSpec.Values) {
					t.Errorf("package-level var %q has no default value", name.Name)
					continue
				}
				lit, ok := valueSpec.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					t.Errorf("package-level var %q default is not a string literal", name.Name)
					continue
				}
				if lit.Value != strconv.Quote(wantDefault) {
					t.Errorf("package-level var %q default = %s, want %q", name.Name, lit.Value, wantDefault)
				}
			}
		}
	}

	for name := range want {
		t.Errorf("generated main.go missing package-level var %q", name)
	}
}
